## The Reuters dataset


In [ ]:
from tensorflow.keras.datasets import reuters
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(
num_words=10000)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/reuters.py:148: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/reuters.py:149: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


In [ ]:
 len(train_data)

8982

In [ ]:
len(test_data)

2246

In [ ]:
i = 2
print(len(train_data[i]))
train_data[i]

139


[1,
 53,
 12,
 284,
 15,
 14,
 272,
 26,
 53,
 959,
 32,
 818,
 15,
 14,
 272,
 26,
 39,
 684,
 70,
 11,
 14,
 12,
 3886,
 18,
 180,
 183,
 187,
 70,
 11,
 14,
 102,
 32,
 11,
 29,
 53,
 44,
 704,
 15,
 14,
 19,
 758,
 15,
 53,
 959,
 47,
 1013,
 15,
 14,
 19,
 132,
 15,
 39,
 965,
 32,
 11,
 14,
 147,
 72,
 11,
 180,
 183,
 187,
 44,
 11,
 14,
 102,
 19,
 11,
 123,
 186,
 90,
 67,
 960,
 4,
 78,
 13,
 68,
 467,
 511,
 110,
 59,
 89,
 90,
 67,
 1390,
 55,
 2678,
 92,
 617,
 80,
 1274,
 46,
 905,
 220,
 13,
 4,
 346,
 48,
 235,
 629,
 5,
 211,
 5,
 1118,
 7,
 2,
 81,
 5,
 187,
 11,
 15,
 9,
 1709,
 201,
 5,
 47,
 3615,
 18,
 478,
 4514,
 5,
 1118,
 7,
 232,
 2,
 71,
 5,
 160,
 63,
 11,
 9,
 2,
 81,
 5,
 102,
 59,
 11,
 17,
 12]


####Decoding newswires back to text

In [ ]:
word_index = reuters.get_word_index()
print(len(word_index))
word_index

30979


{'mdbl': 10996,
 'fawc': 16260,
 'degussa': 12089,
 'woods': 8803,
 'hanging': 13796,
 'localized': 20672,
 'sation': 20673,
 'chanthaburi': 20675,
 'refunding': 10997,
 'hermann': 8804,
 'passsengers': 20676,
 'stipulate': 20677,
 'heublein': 8352,
 'screaming': 20713,
 'tcby': 16261,
 'four': 185,
 'grains': 1642,
 'broiler': 20680,
 'wooden': 12090,
 'wednesday': 1220,
 'highveld': 13797,
 'duffour': 7593,
 '0053': 20681,
 'elections': 3914,
 '270': 2563,
 '271': 3551,
 '272': 5113,
 '273': 3552,
 '274': 3400,
 'rudman': 7975,
 '276': 3401,
 '277': 3478,
 '278': 3632,
 '279': 4309,
 'dormancy': 9381,
 'errors': 7247,
 'deferred': 3086,
 'sptnd': 20683,
 'cooking': 8805,
 'stratabit': 20684,
 'designing': 16262,
 'metalurgicos': 20685,
 'databank': 13798,
 '300er': 20686,
 'shocks': 20687,
 'nawg': 7972,
 'tnta': 20688,
 'perforations': 20689,
 'affiliates': 2891,
 '27p': 20690,
 'ching': 16263,
 'china': 595,
 'wagyu': 16264,
 'affiliated': 3189,
 'chino': 16265,
 'chinh': 16266,
 '

In [ ]:
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])
reverse_word_index

{10996: 'mdbl',
 16260: 'fawc',
 12089: 'degussa',
 8803: 'woods',
 13796: 'hanging',
 20672: 'localized',
 20673: 'sation',
 20675: 'chanthaburi',
 10997: 'refunding',
 8804: 'hermann',
 20676: 'passsengers',
 20677: 'stipulate',
 8352: 'heublein',
 20713: 'screaming',
 16261: 'tcby',
 185: 'four',
 1642: 'grains',
 20680: 'broiler',
 12090: 'wooden',
 1220: 'wednesday',
 13797: 'highveld',
 7593: 'duffour',
 20681: '0053',
 3914: 'elections',
 2563: '270',
 3551: '271',
 5113: '272',
 3552: '273',
 3400: '274',
 7975: 'rudman',
 3401: '276',
 3478: '277',
 3632: '278',
 4309: '279',
 9381: 'dormancy',
 7247: 'errors',
 3086: 'deferred',
 20683: 'sptnd',
 8805: 'cooking',
 20684: 'stratabit',
 16262: 'designing',
 20685: 'metalurgicos',
 13798: 'databank',
 20686: '300er',
 20687: 'shocks',
 7972: 'nawg',
 20688: 'tnta',
 20689: 'perforations',
 2891: 'affiliates',
 20690: '27p',
 16263: 'ching',
 595: 'china',
 16264: 'wagyu',
 3189: 'affiliated',
 16265: 'chino',
 16266: 'chinh',
 2

In [ ]:
i = 0
import numpy as np

decoded_newswire = ' '.join(
    [reverse_word_index.get(i - 3, '?') 
     for i in train_data[i]])

print(train_labels[i])
print(len(np.unique(train_labels)))
decoded_newswire

3
46


'? ? ? said as a result of its december acquisition of space co it expects earnings per share in 1987 of 1 15 to 1 30 dlrs per share up from 70 cts in 1986 the company said pretax net should rise to nine to 10 mln dlrs from six mln dlrs in 1986 and rental operation revenues to 19 to 22 mln dlrs from 12 5 mln dlrs it said cash flow per share this year should be 2 50 to three dlrs reuter 3'

In [ ]:
train_labels[0]

3

In [ ]:
print(len(train_data[0]))

87


In [ ]:
import numpy as np

np.unique(train_labels)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

#### Listing 3.14 Encoding the data

In [ ]:
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results

In [ ]:
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

In [ ]:
print(x_train)


[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


### Change label with one-hot-encode

In [ ]:
from tensorflow.keras.utils import to_categorical
one_hot_train_labels = to_categorical(train_labels)
one_hot_test_labels = to_categorical(test_labels)

In [ ]:
train_labels[0]

3

In [ ]:
one_hot_train_labels[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

### Listing 3.15 Model definition

In [ ]:
a = np.array([1,2,2,3,3,3])
a.shape

(6,)

In [ ]:
from tensorflow.keras import models
from tensorflow.keras import layers

model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(46, activation='softmax'))

#### Listing 3.16 Compiling the model

In [ ]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

#### 3.5.4 Validating your approach

In [ ]:
x_val = x_train[:1000]
partial_x_train = x_train[1000:]

y_val = one_hot_train_labels[:1000]
partial_y_train = one_hot_train_labels[1000:]

#### Training the model


In [ ]:
dataset = model.fit(partial_x_train,partial_y_train,epochs=26,batch_size=600,validation_data=(x_val, y_val))

Epoch 1/26
14/14 [==============================] - 1s 57ms/step - loss: 3.1893 - accuracy: 0.4229 - val_loss: 1.7550 - val_accuracy: 0.6450
Epoch 2/26
14/14 [==============================] - 1s 43ms/step - loss: 1.4938 - accuracy: 0.7053 - val_loss: 1.3442 - val_accuracy: 0.7170
Epoch 3/26
14/14 [==============================] - 1s 43ms/step - loss: 1.1086 - accuracy: 0.7681 - val_loss: 1.2012 - val_accuracy: 0.7440
Epoch 4/26
14/14 [==============================] - 1s 43ms/step - loss: 0.8898 - accuracy: 0.8083 - val_loss: 1.1042 - val_accuracy: 0.7590
Epoch 5/26
14/14 [==============================] - 1s 41ms/step - loss: 0.7222 - accuracy: 0.8485 - val_loss: 1.0189 - val_accuracy: 0.7870
Epoch 6/26
14/14 [==============================] - 1s 42ms/step - loss: 0.5827 - accuracy: 0.8758 - val_loss: 0.9952 - val_accuracy: 0.7900
Epoch 7/26
14/14 [==============================] - 1s 42ms/step - loss: 0.4876 - accuracy: 0.8913 - val_loss: 0.9755 - val_accuracy: 0.7830
Epoch 8/26
14

And finally, let’s display its loss and accuracy curves (see figures 3.9 and 3.10).

In [ ]:
dataset.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

#### Listing 3.21 Retraining a model from scratch

In [ ]:
model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(46, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(partial_x_train,
          partial_y_train,
          epochs=9,
          batch_size=512,
          validation_data=(x_val, y_val))

results = model.evaluate(x_test, one_hot_test_labels) # final check on testing data

Epoch 1/9
16/16 [==============================] - 1s 49ms/step - loss: 3.0880 - accuracy: 0.4183 - val_loss: 1.7002 - val_accuracy: 0.6390
Epoch 2/9
16/16 [==============================] - 1s 38ms/step - loss: 1.4622 - accuracy: 0.6965 - val_loss: 1.2784 - val_accuracy: 0.7200
Epoch 3/9
16/16 [==============================] - 1s 38ms/step - loss: 1.0669 - accuracy: 0.7683 - val_loss: 1.1170 - val_accuracy: 0.7570
Epoch 4/9
16/16 [==============================] - 1s 37ms/step - loss: 0.8442 - accuracy: 0.8179 - val_loss: 1.0599 - val_accuracy: 0.7690
Epoch 5/9
16/16 [==============================] - 1s 39ms/step - loss: 0.6775 - accuracy: 0.8571 - val_loss: 0.9625 - val_accuracy: 0.8020
Epoch 6/9
16/16 [==============================] - 1s 40ms/step - loss: 0.5540 - accuracy: 0.8834 - val_loss: 0.9114 - val_accuracy: 0.8120
Epoch 7/9
16/16 [==============================] - 1s 39ms/step - loss: 0.4314 - accuracy: 0.9100 - val_loss: 0.8976 - val_accuracy: 0.8080
Epoch 8/9
16/16 [===

In [ ]:
results

[0.9746798276901245, 0.7911843061447144]

### 79% accuracy